import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ApolloClerkProvider from "@/components/ApolloClerkProvider";

import "./globals.css";

import 'primereact/resources/themes/lara-dark-teal/theme.css'
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';

const inter = Inter({ weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], subsets: ["latin"]  });

export const metadata: Metadata = {
    title: {
        template: "%s | Forum App",
        default: "Forum App",
    },
    description: "Generated by create next app",
    icons: {
        icon: '@public/logo.svg',
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ApolloClerkProvider>
            <html lang="en">
                <body className={`${inter.className} bg-dark-2`}>{children}</body>
            </html>
        </ApolloClerkProvider>
    );
}
